name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Download Portmap Configuration
        env:
          PORTMAP_CONFIG: ${{ secrets.PORTMAP_CONFIG }}
        run: |
          echo "
client
nobind
dev tun
key-direction 1
remote-cert-tls server
remote 193.161.193.99 1194 udp


<key>
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCzpnj6gT/vSlNp
lIuaPcSSeQLgq2uRI9/0+VWEylugaT2NwCagpOoAsF40ZsEDE0vO6g4+Q68wQKO0
b7RhFLbCee4h9Z6QGcmaMnX4CT9eAb0Axz9/FugkZTchiMRga9kZy/ayNd7S5aF7
rirX2PFf9CaPHmSyEr+1+55rPTt++0D5aap8thjHrWpKop5XxJcM7m+9nG7El4N3
wWV0VYzNoQPxeBfcsScihGoWRR0JmIYVCphjJ38eP6w8QBcwSu1S9XiP0uOBen6I
WBd1vj0d7hiPASWYaPs4aWJvO1N6hyGp64BbDuUO7glgjQVV5EqrbWQuM9yAxC6o
Q+IJqIYnAgMBAAECggEAFvaLdjG5M2QDv3YeVgvZKYPQS1l9+WJliRGpzbxz89Af
7xOFnHkX9BiXIgmUWElKIlumkGzkYr2Qb0rr+pDEP52IQ8z6hJ7XNx+GFrtP3ztH
pmbRhfQuniBV6LJrr4t5h6Obl/Hs1nZFquJ7VXXEfKhfmWGgK2bcHG3aNQjxpuxN
0ml4nZ9jGy67vqoOW1QKz0V7zNevfKw2daJ8GNS5vaMa0OpWJ8Etr+JLAsFDVJZF
+xB7fQqEejQArrvbGGpQgyw5qRUnCfsXdDo4MBJUkK8yhoXstxRAfPC09xIylQQp
OKKGekeRV4FfK4ibUYEhxjto34eTVH4k1OjO82sLWQKBgQDlSj2houPScd0qyj81
xWs5vzE/iIFM/YazmOkq27wtcocq1GDI3woHRPbbwIpmYBsmBAI2605u06/h8u5x
WoWTKO0yCEixUIl/ND7SxJID1Y1w/aTiKGFkLdDiZdvUamuc5XPEcLwKmnOTWj6K
LPkjR/Ek28Xt4+ZV06rkughnDQKBgQDIk+dVzDjfXJJ1TidrN/irOMQXuBIbUYqm
b5vCVVee6Mf+s5/RO/RGTs71E2AhqCBs5C/wWZ+/f9+9ADvdI96Q+URM2I9LvDLf
BFjxQTdT/dlrtabaT8JqawlkJGnd4jbknAOiOG7rOumOWmoFIl1wcjWmnb7rhi07
Su+5ALhVAwKBgQCuUcgTeASevQR5gLOXzNSdXZcyhzROdT0Qk8NJWy9wme7biAVh
EfjM2AiZv4M5G/3n5ApO+Ixzw6qnLItNUJXW8LmMXTHu5Jz0QaM1mE6ubZAQBDZz
3mFUyWRSi0Aa+SGBcgyWn2LG6O/Paj+7yz9KLGrQK+oJ10cJn1gAdtLmjQKBgFKc
F/tOUV4tUmTd+349Xz2l852RQmPeAazq6svvOldIqJZOhNQ4TTNn4fUuNbmm9TPk
B5qGTzUgBZZiMkWyMEilYWwFBX+703fm4nr60T7WnmWuOzpO/1O1IfkMxk2Mje86
EoUNmSFo8iifNGtI7BMT9uTYs3ltmdOB2ZnoogLhAoGANnNgE8NbbsKdoklHjnCT
wE2KX/GUSMo4c5AeeIgFaVLIYAjbQFRnOufk1Mj3LctBDFIzMZ7zovxnNKGQLiO0
6eXYX3/T3mpGXRjGhuJZkHDxpgLnqRvIAceRXOKAPu0BlTrHnMqZSgPLzf4k3HJA
Bzp2Yts58IVZfYS6xjxTo2Q=
-----END PRIVATE KEY-----
</key>
<cert>
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgIDCPKNMA0GCSqGSIb3DQEBCwUAMBUxEzARBgNVBAMMCnBv
cnRtYXAuaW8wHhcNMjUwMTEzMDg1OTI3WhcNMzUwMTExMDg1OTI3WjAYMRYwFAYD
VQQDDA11Z2x5OTY5LmZpcnN0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEAs6Z4+oE/70pTaZSLmj3EknkC4KtrkSPf9PlVhMpboGk9jcAmoKTqALBeNGbB
AxNLzuoOPkOvMECjtG+0YRS2wnnuIfWekBnJmjJ1+Ak/XgG9AMc/fxboJGU3IYjE
YGvZGcv2sjXe0uWhe64q19jxX/Qmjx5kshK/tfueaz07fvtA+WmqfLYYx61qSqKe
V8SXDO5vvZxuxJeDd8FldFWMzaED8XgX3LEnIoRqFkUdCZiGFQqYYyd/Hj+sPEAX
MErtUvV4j9LjgXp+iFgXdb49He4YjwElmGj7OGlibztTeochqeuAWw7lDu4JYI0F
VeRKq21kLjPcgMQuqEPiCaiGJwIDAQABo4GWMIGTMAkGA1UdEwQCMAAwHQYDVR0O
BBYEFC7jibc7vj/M4gwDNy2VsciMPiQGMEUGA1UdIwQ+MDyAFDQWG5a5jOCmYTlU
8AaE1GKdQKwkoRmkFzAVMRMwEQYDVQQDDApwb3J0bWFwLmlvggkA2k08psXWVw4w
EwYDVR0lBAwwCgYIKwYBBQUHAwIwCwYDVR0PBAQDAgeAMA0GCSqGSIb3DQEBCwUA
A4IBAQALxlLGNOP06b+ytFHaQdvD9Wi0UZj58v6Z4hochCgU9jxkX/L1NIzG21S1
2bO62+VwxZCNzqUZdYSLhUA3ojL8iS8gQmR3GL6gMDRXMk4TDEAsq2Actv1SRs8j
wcZbCEdH0V/EXW9435Vt/CKucDX9TRvjszpgReQZGKkyn4sXokmmZN9hCIsezkvG
Qp/vHKPPDYkQ47fp5BYrMgZznYohTgjcpHBZH1avWlqxmwRhiS2AWfemffgS8jjw
PiG5m1wDKlaNtEX+BvsDouh7qXAYu/r2S2iMOcWa2Bsud9NOrZvgPo0tWyD/b5f6
Z8geWFaZLuiereClXJaBS65EhmXs
-----END CERTIFICATE-----
</cert>
<ca>
-----BEGIN CERTIFICATE-----
MIIDMjCCAhqgAwIBAgIJANpNPKbF1lcOMA0GCSqGSIb3DQEBCwUAMBUxEzARBgNV
BAMMCnBvcnRtYXAuaW8wHhcNMTcwMjE2MTAyMDM2WhcNMjcwMjE0MTAyMDM2WjAV
MRMwEQYDVQQDDApwb3J0bWFwLmlvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAuHiffM/kU4lRZ4OrFRXYLCiI7eJubuAnzySuLkug0BkypuB6ihW8f8pT
HcsTYGt7gt0CSzAe0f7j/SXGAkWFtAvURZAV/PM0VyB/yiejS0gTZXqPLMQCMvM3
TkRECAnybWT3HoJAqWukuD9N9F98LrOGYkNy5gnKirVYB9Envztb/0oqvHcntmcJ
Z598NxKa9a490UKKQMHY898EenXPf1yJmT4CFSfcZGO4D5iWMlE87oVNlmle4YoH
HSrAUJRActjhZLaO2+ymnGUxok4gVum8sw8ruCVmobXMViG9trzJMRAtawRezhCp
rMwSeRhCDC/1Z3KHDuUFQx7mTDI8WwIDAQABo4GEMIGBMB0GA1UdDgQWBBQ0FhuW
uYzgpmE5VPAGhNRinUCsJDBFBgNVHSMEPjA8gBQ0FhuWuYzgpmE5VPAGhNRinUCs
JKEZpBcwFTETMBEGA1UEAwwKcG9ydG1hcC5pb4IJANpNPKbF1lcOMAwGA1UdEwQF
MAMBAf8wCwYDVR0PBAQDAgEGMA0GCSqGSIb3DQEBCwUAA4IBAQBj8A0/6F2iNR32
U6SCMtLPumJpdIaO1xtZ6Vilxpe0WX5zrtRL8A2Lz/XCHm3VwuM2P0rTFtncax4r
Rpy3RIRZ/T+Un8H1eTjZ7HqHWnuD4z4FLl2kZ0QtFGXBTSzfzCVjm4Z/6jsxT00t
0FSLILZYhJj7ndJag6D8LnNsoYeBX5qpqhesg9L3DL9hNwRNlomC+LMCK/oYL9KS
o/Zn9VBcjJAxGAX4XsfCLBFWVVhxIgokEbLfFwJZmmcLgxMtBlnh3R0O2WRd54Z3
0zNxMJhGg61wzzBLZn3D3Q2D8wr+OxEnVKiUKL9T3ih1TDQzSMt5b2cXL2y94NaF
uvwm+iR9
-----END CERTIFICATE-----
</ca>
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
42bb453ee0df769b134e57435c88a745
927d7fd254987077bdf822567410ed73
f816335742f5737b0ad1e290ebe4e669
1a8edad3f23aff0c4872172f1e3c30d2
025cddbfd2dfdcecb3ef2f1f4e531c60
1e9c48e1abe96c46c80eaa5f121a72b5
e7b194a6a0abc06fbc736abc41122f5d
aa0c7ddcfc80455983ac7e6cb005d0c7
7ef5ed9c20cebe4481a733a5b4e63ba8
74a0710bcd0b732d5b79ef6e2032c0c2
6e1cbe01873367524a28d582901ceed1
241fe087a8e84467c9c790c7af719622
413fcc77b130629258db8a8e6678f53c
7cd213dc82e5b613ca310642cfbb6cb5
63111511e467f45417d9950035827d30
43b13e9e01f0c42481edb1fe1808806b
-----END OpenVPN Static key V1-----
</tls-auth>
key-direction 1
" > portmap.ovpn

      - name: Start OpenVPN Connection
        run: sudo openvpn --config portmap.ovpn &

      - name: Test SSH Access
        run: |
          echo "Your portmap tunnel is active. Connect via the provided SSH details."
