name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Download Portmap Configuration
        env:
          PORTMAP_CONFIG: ${{ secrets.PORTMAP_CONFIG }}
        run: |
            echo "$PORTMAP_OVPN" | base64 -d > portmap.ovpn

      - name: Start OpenVPN Connection
        run: sudo openvpn --config portmap.ovpn &

      - name: Test SSH Access
        run: |
          echo "Your portmap tunnel is active. Connect via the provided SSH details."
